### ISSUE TITLE
0.5.3 dump is likely missing padding in non-4-byte-column cases

### ISSUE THREAD

**Issue by bloerwald** [wowdev/WoWDBDefs#10]
https://github.com/wowdev/WoWDBDefs/commit/2ec0ffc679b973a958b6c640722a481a105d9878#r28083274

**Comment by bloerwald** [comment]
according to @barncastle there was no padding in 0.5.3 files. apparently this is a 6.0.1 thing. Thus, the dbds are right and this can be closed, I guess.

**Comment by barncastle** [comment]
Yeah sorry forgot to update this issue. Can confirm this in file has no padding. 
Also to note, in 6.0.1 this isn't true for all cases. I'll create an issue and work through these when I get a chance.
