### ISSUE TITLE
download 

### ISSUE THREAD

**Issue by blacknightt1** [wowdev/WoWDBDefs#124]
Hello
Until a few days ago, the dbc files could be downloaded from your good site, but now it is not possible, why?
I need the CSV item file

https://wow.tools/dbc/?dbc=item&build=9.2.7.45745#page=1

thank you

**Comment by Marlamin** [comment]
That functionality is no longer available due to excessive scraping. I'm working on a guide explaining how people can do this manually and will hopefully have it out this month.

Also, this is not related to WoWDBDefs, closing.
