### ISSUE TITLE
unk_8c/unk_90 flags are parent columns

### ISSUE THREAD

**Issue by bloerwald** [wowdev/WoWDBDefs#13]
from https://github.com/wowdev/renderservice/issues/10 via @Shauren:

```c++
    bool HasParentLookup;
    uint ParentIdColumn;
    uint ParentIdHotfixColumn;
```

- [x] sed those comments to be an annotation, e.g. `$parent$` in the defs we have (only known for 8.0.1)

**Comment by MMOSimca** [comment]
HasParentLookup = 1 and (int, not uint) ParentIdColumn = -1, then the column specified by ParentIdHotfixColumn is the column we use for $relation$ attributes.

HasParentLookup = 1 and ParentIdColumn > 0, then the column specified by ParentIdHotfixColumn is something else. we can debate what to name but i'm not convinced parent is the right name.

I'd also suggest these 3 fields be renamed/retyped as such:
`bool HasIndexLookup
int IndexIdColumnInFile
int IndexIdColumnInClient`

**Comment by Shauren** [comment]
> HasParentLookup = 1 and ParentIdColumn > 0, then the column specified by ParentIdHotfixColumn is...

In this case its always equal to ParentIdColumn 

as for "hotfix" - its used for hotfixes (ClientDbReply, ClientHotfixMessage, ClientAvailableHotfixes) - the stuff that goes into DBCache.bin

**Comment by bloerwald** [comment]
see pull request for updated merge of `parent` and `relation` and generalised annotations.
