### ISSUE TITLE
Clarification on column annotations

### ISSUE THREAD

**Issue by gtker** [wowdev/WoWDBDefs#131]
Hello,

I have written a [Rust library](https://github.com/gtker/wowdbdefs-rs) for this format, but I'm unclear on what exactly the `noninline` and `relation` annotations actually mean.

I'm also wondering if there's a way to map the enums/flags from [here](https://github.com/Marlamin/wow.tools/blob/master/dbc/js/flags.js) to individual tables without too much hassle?

Thanks :)

**Comment by Marlamin** [comment]
`noninline` refers to columns that aren't stored in line with row data but separately in the DB2 files. `relation` means a column is/has a foreign key to a different table. When a `relation` is `noninline` it is stored in a separate part of DB2 files called the relationship mapping. You can find more information on the DB2 format [here](https://wowdev.wiki/DB2#Structure_8).

As for a way to get the enums/flags into DBD, we have a discussion set up for that (and other things) [here](https://github.com/wowdev/WoWDBDefs/discussions/109),

**Comment by gtker** [comment]
Thanks, any time estimate on when/if enums/flags will arrive?

**Comment by Marlamin** [comment]
Nope, I want to get the manifest out first. Also going to take it easy with the WoW stuff so hoping someone else will take on the flags/enums task.

**Comment by gtker** [comment]
Understandable.

I would not mind adding enums/flags for at least 1.12/2.4.3/3.3.5, but I don't care about anything newer than that.

I noticed that you're mentioning automatic updates to wowdev.wiki, do you know who I should talk to in case I want something similar for network messages? I have [almost all messages definitions for 1.12/2.4.3/3.3.5 at wow_messages](https://github.com/gtker/wow_messages) that generates some [documentation](https://gtker.com/wow_messages/docs/smsg_update_object.html) and it would make sense to also just generate docs for the wiki.

**Comment by Marlamin** [comment]
I'll link that to the person who was working on automated wiki updates at the time, thanks.

**Comment by gtker** [comment]
Thanks. I don't mind implementing it myself if it's relatively easy since it would just be my documentation generator but slightly modified I just don't know who's really responsible for the Wiki and I didn't want to just spam upload several thousand new pages at once.

Thanks for the effort on the project it's incredibly useful for autogenerating DBC parsers, and thanks for the quick answers. :)
