### ISSUE TITLE
WorldMapOverlay doesn't have a modern definition or no longer exists?

### ISSUE THREAD

**Issue by AlexeyMatskevich** [wowdev/WoWDBDefs#156]
I was trying to find a way to get area offsets relative to the world coordinates, or the coordinates of their start and end.
For the sake of this, I tried using WorldMapArea. 
As I understand it, the current versions of the definitions don't have a description for version newer than 8.0.1.26321.
https://github.com/wowdev/wow-listfile still has this file, based on this I have a question. In modern versions of the client this file is not present, or there is no definition for exporting it?

**Comment by Marlamin** [comment]
That file doesn't exist anymore, try UIMapAssignment instead, it serves a similar purpose to that file.

Not a DBD issue so closing.

**Comment by jgwinner** [comment]
It's really data mining. A lot of tools are now obsolete as people have moved on and code grows stale. 

Hats off to the DBD's having this info.

Hats off to @Marlamin and the team for still keeping old versions in the database. It helps when trying to modernize some apps so you can figure out what happened.
