### ISSUE TITLE
SoundEntries data?

### ISSUE THREAD

**Issue by trcrsired** [wowdev/WoWDBDefs#163]
I saw the data is on wowtools and it says it is no longer available at client side. But is it possible to get an old version of it (like WoD version)? I am trying to make an addon that would play retail music on classic

**Comment by trcrsired** [comment]
can you provide a download for soundentries.csv from wowtools? Thank you

**Comment by Marlamin** [comment]
Try the GW2Archive DBC/DB2 archive linked [here](https://archive.wow.tools/).

This is not a DBD issue, so closing.
