### ISSUE TITLE
todo - trailing underscores

### ISSUE THREAD

**Issue by barncastle** [wowdev/WoWDBDefs#17]
Fields in the following have trailing underscores
- BannedAddOns
- GarrMission
- GarrMissionTexture

**Comment by Marlamin** [comment]
Are those from official names? Eww.

**Comment by barncastle** [comment]
I was dubious but apparently so - just checked renderservice...
Personal preference is to burn them with fire but thats up for debate!

**Comment by Marlamin** [comment]
+1 🔥

**Comment by bloerwald** [comment]
Iirc those are fields that are `union`’d to a real type, `C2Vector` and `md5digest`. 

Since we don’t do that, i think I’m fine with just removing the character and keeping it as verified. 

Then again, I don’t see this as a big issue actually needing a change either.

**Comment by Marlamin** [comment]
Am fine with fixing these for purely aesthetic reasons.
