### ISSUE TITLE
todo - map.dbd $noninline,id

### ISSUE THREAD

**Issue by barncastle** [wowdev/WoWDBDefs#18]
8.0.1.26231 has an IndexTable but is marked `$id$ID<32>` - this should be `$noninline,id$ID<32>`.
Need to verify the associated builds also apply to this change.

**Comment by Marlamin** [comment]
Map is the only dbd that has had significant manual work done. Probably
needs a complete check.

**Comment by bloerwald** [comment]
801 definitions are renderservice generated. Did we fuck up at merging?

**Comment by Marlamin** [comment]
This might only be an issue for Map, which was manually created and then merged into later.
