### ISSUE TITLE
Converters to other formats (JSON/XML)

### ISSUE THREAD

**Issue by Marlamin** [wowdev/WoWDBDefs#29]

**Comment by Marlamin** [comment]
Initial conversion to JSON works ([see DBDefsConverter](https://github.com/wowdev/WoWDBDefs/tree/master/code/C%23/DBDefsConverter)), I did have some issues getting stuff to serialize properly into XML (dictionaries not being serializable being the biggest issue) so I'll leave this open in case someone wants to tackle that.

**Comment by barncastle** [comment]
@Marlamin Will share mine when I get back. Its a few tweaks away from producing the same schema as the above.

**Comment by barncastle** [comment]
Referenced formats are completed via cb970ee and e2807aa
