### ISSUE TITLE
Pre-wod definitions

### ISSUE THREAD

**Issue by skarnproject** [wowdev/WoWDBDefs#43]
How far is the progress on pre-wod branch? Merge maybe?

**Comment by Marlamin** [comment]
Not ready yet. If you're looking for a specific set of definitions we can look into merging those based off of @barncastle's original defs if he still has those around somewhere.

**Comment by Marlamin** [comment]
Did a manual pass at merging some of the pre-wod branch in 4c16c28, will need further pass(es) to merge versions I missed/wasn't sure about/need manual checking.

**Comment by barncastle** [comment]
Obligatory message to let you know we've now merged this into master.
PRs are always welcome for any changes/fixes!
