### ISSUE TITLE
Spell dbc Field_4_0_0_11927_104 --> BonusCoefficient

### ISSUE THREAD

**Issue by Ovahlord** [wowdev/WoWDBDefs#70]
So this field was pretty easy to identify. Spells that use that field have a tooltip which shows a internally calculated damage value based on attack power like Heroic Throw. Usually spells that use attack power based values have their formula inside of their tooltips but spells that have that field being set are always attack power based and perfectly align with the tooltip values when doing the calculations manually.

The old pre 4.x field was EffectBonusCoefficient which was an array with 3 values for each spell effect but apparently Blizzard has refactored that handling when splitting the Spell.dbc into multiple files so that's most likely just a leftover.

**Comment by bloerwald** [comment]
Thanks!

I tried to somehow verify it and only was able to see that some BC are roughly half of the EBC value, so seems to be fine. Added in 3fdd76174.
