### ISSUE TITLE
ItemSparse.dbd incorrect in 9.1.0.38312

### ISSUE THREAD

**Issue by MaxtorCoder** [wowdev/WoWDBDefs#80]
After some investigating I found out that ItemSparse.dbd is incorrect in 9.1.0.38312, fields are incorrect.

Left is latest 9.0.5, right is latest 9.1.0.
9.0.5 is completely correct and shouldn't be changed in 9.1.0
![image](https://user-images.githubusercontent.com/17987686/115215059-6a942680-a103-11eb-831e-20eb7623f3ab.png)

**Comment by Marlamin** [comment]
Should be fine now, ContentTuning and RequiredAbility seemed to be swapped around. Please check again!
