### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Marlamin** [wowdev/WoWDBDefs#88]
Turns out after all the time we haven't done this. Not sure how relevant it is for files like this (especially as we base stuff on Blizz names) but probably good to have still.

**Comment by stivenzam** [comment]
This would be a nice thing since I would like to use your great definitions for parsing db2 files. They are just more eye / user friendly.

**Comment by bloerwald** [comment]
What about
```
.github/workflows
analytics
definitions
schlumpf
README.md
```
- CC BY-SA 4.0 (-NC would be neat, but wowhead)
```
code
exedumper
```
- GPL 3.0 (to avoid wowhead being a wowhead, at least in spirit), or
- BSD-3-Clause (to keep it simple and permissive)

?

**Comment by Marlamin** [comment]
CC BY-SA 4.0 sounds good for defs, I don't really care to add a NC as SA would cover most worries.

For the code I don't really care, something like BSD-3 or something even more permissive would be fine in my books.

**Comment by Marlamin** [comment]
Also, might be worth mentioning that DBCD is MIT and I don't know what it means if we (re)license any of the DBDefsLib code (which would also affect https://github.com/wowdev/DBDefsLib).

**Comment by bloerwald** [comment]
I looked and didn’t see any licenses and still don’t, but MIT is also fine I guess. Main difference is that BSD-3/4 forbids them advertising wowhead with our names, something they probably.. won’t.

**Comment by Marlamin** [comment]
https://github.com/wowdev/DBCD/blob/master/LICENSE

**Comment by funjoker** [comment]
@Marlamin if you want to relicense DBCD from MIT to BSD you simply can ask your contributors :D
For me, i agree with everything that keeps it opensourcly and useable hehe :D

**Comment by funjoker** [comment]
Would be BSD or any other suggested license compatible with GPLv2 or GPLv3 ?
We currently using DBCD inside WowPacketParser (if you want to relicense it)

https://github.com/TrinityCore/WowPacketParser#provided-third-party-libraries
https://github.com/TrinityCore/WowPacketParser/blob/master/COPYING

**Comment by Marlamin** [comment]
> @Marlamin if you want to relicense DBCD from MIT to BSD you simply can ask your contributors :D
> For me, i agree with everything that keeps it opensourcly and useable hehe :D

I don't want to deal with relicensing DBCD, just wanted to note it uses a library were talking about possibly giving a license, which might have repercussions.
