### ISSUE TITLE
ChrRaces

### ISSUE THREAD

**Issue by funjoker** [wowdev/WoWDBDefs#90]
locstring Name_RS_lang? // quest text $RS
locstring Name_RS_female_lang? // quest text $RS
locstring Name_RS_lowercase_lang? // quest text $rs
locstring Name_RS_female_lowercase_lang? // quest text $rs
locstring Name_RL_lang? // quest text $RL
locstring Name_RL_female_lang? // quest text $RL
locstring Name_RL_lowercase_lang? // quest text $rl
locstring Name_RL_female_lowercase_lang? // quest text $rl

i don't know any $rs or $rl usage in quests...
can someone tell me what this is about?

otherwise i don't think this naming is correct

**Comment by bloerwald** [comment]
The names and selection logic was taken from the client back when I added it and I’m fairly sure it was correct then. What indication do you have for it being wrong? Did you check other languages?

**Comment by funjoker** [comment]
I ran string search on all tables in TC (bruteforced data). I was unable to find any. Only find was $rs which was clearly <race>s… just the Race appended by s. Looking at the locales it is clearly just an s appended due to English language. e.g the Plural of Human is humans. In German it’s Mensch and Menschen.

**Comment by bloerwald** [comment]
9.0.2.36839 has
![image](https://user-images.githubusercontent.com/2866005/140194231-ee7e74fc-0a90-42d3-ab0a-5048bc512144.png)
![image](https://user-images.githubusercontent.com/2866005/140194382-03eae833-6a4a-43b5-a5f6-e5517cd3fa89.png)
![image](https://user-images.githubusercontent.com/2866005/140195911-96968d07-f0e7-4214-b4b8-2babc43b2d73.png)
![image](https://user-images.githubusercontent.com/2866005/140195927-e204e953-940b-4eb9-ab5f-3ad1cb005df0.png)
So I claim it is correctt, except that I apparently flipped the R and S.

**Comment by funjoker** [comment]
Blizzard gave us a present.

#95

**Comment by jgwinner** [comment]
That code is fascinating - can I ask what it's from?

**Comment by bloerwald** [comment]
> That code is fascinating - can I ask what it's from?

The snippets above are decompiled code from the client executable.
